### ISSUE TITLE
Hookless in MetaCTF 2021 writeup

### ISSUE THREAD

**Issue by tacbliw** [nobodyisnobody/write-ups#2]
Hi, in your [writeup ](https://github.com/nobodyisnobody/write-ups/tree/main/MetaCtf.2021/pwn/Hookless) for `Hookess` challenge in MetaCTF 2021, you wrote
```
we probably could also have leaked the address of the bss or program base, via ld.so vars..

and overwrite a GOT entry... we left that as an exercise for the most motivated...
```
I wonder how to leak program base from ld.so?
Thanks

**Comment by nobodyisnobody** [comment]
Look at this capture, when using gef extension,
you can do:  scan ld.so binary

it will print you reference to binary mapping zone (exec,bss,etc..) in ld.so

like you can see, in the picture:

![hookless ld so](https://user-images.githubusercontent.com/79855767/173289296-7a53897a-033e-40b4-ba9f-f16064e55160.png)

you can see that there are many reference to binary addresses in ld.so,

that we can leak too, to calculate program base,

and eventually overwrite a GOT entry.

**Comment by nobodyisnobody** [comment]
Hi,
I answered you in the comments

best regards.
